default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: pizza_factory_app_development
  username: ketan
  password: 'bluebash@123'
  host: localhost
  pool: 5
  timeout: 5000


test:
  <<: *default
  database: pizza_factory_app_test

production:
  <<: *default
  database: pizza_factory_app_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
